import type {Metadata} from 'next'
import {Rubik} from 'next/font/google'
import './globals.css'
import NavBar from './components/NavBar/NavBar'

const rubikSans = Rubik({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${rubikSans.variable} antialiased`}>
				<NavBar />
				{children}
			</body>
		</html>
	)
}
